- name: Setup .NET Core SDK
  uses: actions/setup-dotnet@v4.0.1
  with:
    dotnet-version: 6.0
    dotnet-quality: null
    global-json-file: null
    source-url: null
    owner: null
    config-file: null
    cache: null
    cache-dependency-path: null
